# Generated by Django 4.2.5 on 2023-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bustime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30, verbose_name='Bus Name')),
                ('b_from', models.CharField(max_length=10, verbose_name='From')),
                ('departure', models.CharField(max_length=10, verbose_name='Departure')),
                ('to', models.CharField(max_length=10, verbose_name='To')),
                ('arrival', models.CharField(max_length=10, verbose_name='Arrival')),
            ],
        ),
    ]
