# Generated by Django 4.2.5 on 2023-10-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustime',
            name='arrival',
            field=models.TimeField(verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='bustime',
            name='b_from',
            field=models.CharField(max_length=15, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='bustime',
            name='departure',
            field=models.TimeField(verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='bustime',
            name='to',
            field=models.CharField(max_length=15, verbose_name='To'),
        ),
    ]
