# Generated by Django 4.2.5 on 2023-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_bustime_arrival_alter_bustime_b_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busroute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=40, verbose_name='Stop')),
                ('depart', models.TimeField(verbose_name='Depart')),
            ],
        ),
    ]
