# Generated by Django 4.2.5 on 2023-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_busroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='depart',
        ),
        migrations.AlterField(
            model_name='busroute',
            name='stop',
            field=models.TextField(verbose_name='Stop'),
        ),
    ]
