# Generated by Django 4.2.5 on 2023-10-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_remove_busroute_depart_alter_busroute_stop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busroute',
        ),
    ]
