# Generated by Django 4.2.5 on 2023-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_delete_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
